#!/bin/bash
ffmpeg \
-f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor \
-f pulse -ac 2 -ar 48000 -i bluez_sink.41_42_33_39_14_D4.a2dp_sink.monitor \
-f pulse -ac 2 -ar 44100 -i alsa_input.pci-0000_00_1b.0.analog-stereo \
-filter_complex amix=inputs=3 \
-acodec libvorbis \
-f x11grab -r 30 -s 1366x768 -i :0.0+0,0 \
-vcodec libx264 -preset ultrafast -crf 15 \
-threads 4 \
/home/patrick/Videos/vlogs.mkv

#-vcodec libx264 -preset veryfast -crf 16 \
#-f pulse -ac 2 -ar 44100 -i alsa_input.pci-0000_00_1b.0.analog-stereo \
#-acodec libmp3lame -ar 44100 -q:a 1 \
#-pix_fmt yuv420p \
